### ISSUE TITLE
Add an optional pane overview

### ISSUE THREAD

**Issue by foreveryone1** [pjeby/pane-relief#1]
A way to view the opened documents in the sidebar, would make things much easier for those accustomed to tabbed working environments.

![](https://cdn.discordapp.com/attachments/707816848615407697/820996470970777610/unknown.png)

edit: oh dear, it seems I forgot to label this as a feature request, sorry!

**Comment by pjeby** [comment]
This would be nice to have (especially when maximizing panes), but it's unlikely to happen any time soon.

I imagine the UI would include a number next to each pane (so you know which one you want to jump to or move to), and perhaps a way to show the history, and a highlight to indicate the currently active pane.

**Comment by pjeby** [comment]
I find that I am now using Quick Switcher ++ for this purpose, having assigned a hotkey for its "Open in Editor Mode" command.  This brings up an overview of the currently open markdown files, in workspace leaf order, and allows selection via the keyboard.  So I would suggest that as an interim solution.

**Comment by pjeby** [comment]
The "koncham workspace" plugin now provides this feature, in a manner compatible with pane relief.

I'm leaving this issue open for now, as a reminder to link to it in the README in a future release.
