### ISSUE TITLE
Please enable this Plugin for mobile

### ISSUE THREAD

**Issue by vaughnmonkey** [pjeby/pane-relief#12]
I don't know if its easy or even possible but I absolutely love your plugin on my desktop obsidian. I would be eternally greatfull if you could somehow get it to work/be compatible with obsidian mobile, specifically andriod for me. 

Even if its not something thats possible or that you have time to do, Thank you for making such a great plugin and sharing it with us

**Comment by pjeby** [comment]
You can try enabling it yourself by removing the isDesktopOnly line from the manifest.json in the plugin directory, and then you can see for yourself if it does what you want it to on your mobile platform.  (I am not currently set up to do development on the mobile version of Obsidian.)

Let me know what does or doesn't work.

**Comment by pjeby** [comment]
Another user (issue #17) tried this and it doesn't work on iOS at least.  Assistance from an iOS developer is needed to move this forward any.
