### ISSUE TITLE
Feature request: open in adjacent pane

### ISSUE THREAD

**Issue by ko13** [pjeby/pane-relief#19]
I like having open two panes. However, I am missing a functionality in Obsidian, that I can open links from one pane in the other without opening new panes all the time.
I would wish for a hotkey or menu option to open a link in the adjacent pane. Or even to choose the number of the pane to open the link.
Excalidraw has such an option but that only works from inside excalidraw drawings. Would be cool to have this in other files as well and I thought it fits really nice into the pane-relief plug-in.

**Comment by pjeby** [comment]
Actually, Obsidian core provides two ways to do this already:

1. If you pin the pane you want to keep the same, Obsidian will open links in the next-most-recently-used pane (i.e., the other open one, if that's all you have)
2. If the pane with links is in preview mode, you can drag links to the pane header of the other pane  (this also works for file explorer items, recent file items, pane relief history menu items, starred items, the quick explorer current-file display, etc. -- all can be dragged to the pane header you want to open them in)

The "pin" function can be found in the "More options" dropdown for the pane; there is also a command you can assign a hotkey to.  So you can just turn the pinning on or off from the keyboard as needed.

**Comment by ko13** [comment]
Thank you very much for your fast reply. That was helpful. I didn't know this functionality existed.
