### ISSUE TITLE
FR: move back / forward buttons to the document title bars...

### ISSUE THREAD

**Issue by olearydj** [pjeby/pane-relief#23]
It would be nice if the ←→ arrows on the obsidian title bar could be moved / duplicated to the document title bars. This would be in keeping with pane-relief's per document history.

I know... real men use hotkeys. Me too, mostly.

**Comment by pjeby** [comment]
https://github.com/pjeby/pane-relief/blob/master/README.md#per-pane-navigation-buttons

**Comment by olearydj** [comment]
Oh geeze. Sorry!

**Comment by pjeby** [comment]
No problem, just figured it'd be easier for me to paste the link than copy the docs here.  ;-)
