### ISSUE TITLE
Question: "dead" margins on the left and right of panes

### ISSUE THREAD

**Issue by Randy-Astle** [pjeby/pane-relief#26]
First, let me say that I really like the extensions you've created -- and your responsiveness to requests or feedback.

My question may not be relevant to the Pane Relief plugin, but I suspect you will understand the underlying cause and be able to provide some direction.

There is a margin on the left and right of an editor pane that seems "dead" for lack of a better word. If I click in this margin, the focus shifts to that editor pane, but the caret is inactive. (I have Vim key bindings enabled.) If the editor is in normal mode, the cursor is solid and non-blinking and non-responsive. If the editor is in insert mode, the caret disappears, and typing doesn't insert text.

I have to click again farther into the editor pane before the cursor starts to blink and respond to commands.

If Leaf Auto Width is enabled, these margins are quite wide. If I disabled Leaf Auto Width and set Leaf Width on Desktop to 850 (Sliding Panes settings), I can minimize the width of the margins, but I can't eliminate them.

Is there a way to configure Obsidian or Pane Relief to enable editing if the pane is clicked in one of these margins? Or perhaps, pressing the ESC key will put the pane into editing mode?

A different point: it would be handy if the note title is being edited (or just has the focus because I clicked on it), to shift to editing the note by pressing ESC.

Thanks,

Randy

**Comment by pjeby** [comment]
I see what you mean but I have no idea what the deal is with that -- It happens with the sandbox vault and no plugins, so it looks like an issue with Obsidian and should probably be reported as a bug via the forums.

**Comment by Randy-Astle** [comment]
Thanks -- I'll do that.
