### ISSUE TITLE
Bugs appearing when coming back to unmaximised panes when several panes are opened (bug when Sliding Pane plugin enabled)

### ISSUE THREAD

**Issue by Oskiator** [pjeby/pane-relief#28]
Here picture will speak more than words.
**Obsidian : v0.15.9**
Bug happening **when the plugin "Sliding panes" is enabled**

## Repeat the bug
1) Enable pane-relief and Sliding panes plugins
2) Open several notes and maximise one note containing links
3) Follow one link and come backward
4) Unaximise the note => The pane is now larger and overlap other panes (see example below)

The bug happens when following all times when a link in the maximised pane and also sometimes after editing the content of the maximised note (but here I don't know exactly what trigger the bug).

### Before maximising (everything ok)
![image](https://user-images.githubusercontent.com/96892939/185103748-51d18021-cb6e-464d-8b64-2885280632a5.png)

### Maximising the central pane (everything ok)
![image](https://user-images.githubusercontent.com/96892939/185103791-a0643570-e238-45de-b8e4-d51560e74101.png)

### Unmaximising, coming back to normal view => buggy
![image](https://user-images.githubusercontent.com/96892939/185104015-5945027f-0668-46a0-9b4a-2edf7390c145.png)
=> Orange : a part of the previous panes disappeared behing the one that have been maximised.
=> The one that have been maximised stay larger than before

#### When scrolling left
![image](https://user-images.githubusercontent.com/96892939/185104398-0eaedccf-38d3-4d23-9263-e6b08197ae67.png)
=> When scrolling left we see that panes are going behing the one that have been maximised

#### When scrolling right
![image](https://user-images.githubusercontent.com/96892939/185104651-7285d20c-0c14-4291-9866-c41507a6b9d2.png)
=> When scrolling right, curious things happen 🙂

### Workaround
Close de buggy note and reopen it.

Thanks for your work 😉 

Michaël

**Comment by pjeby** [comment]
Unfortunately, there is nothing I can do about this, it's part of how Sliding Panes works.  You might try enabling fixed width panes or disabling stacking, but I don't know if that will fix it.

Because of the various issues with that plugin, I am actually no longer using it myself.  Instead I'm using a replacement I'm working on that will be built into a future version of Pane Relief.  (At the moment it does not support stacked panes or rotated headers, however, only fixed width panes.)

**Comment by Oskiator** [comment]
Thanks for your answer ! I will so follow your work.

**Comment by pjeby** [comment]
Pane Relief 0.3.1 now has a simple sliding panes replacement that works on Obsidian 0.15.9, and is compatible with the new "tab stacking" feature of Obsidian 0.16.2 (currently an Insider-only release).  Tab stacking is a core replacement for the stacking panes and rotated headers provided by the Sliding Panes plugin, and it works properly with maximizing and de-maximizing (as does Pane Relief's simple sliding panes feature).

Whether you use the Pane Relief sliding or the Obsidian 0.16 stacking, you should disable the original Sliding Panes plugin first and restart Obsidian.  Pane Relief sliding and Obsidian tab stacking can be combined, or you can just use one.  Sliding is toggleable on a per-window basis, and stacking is toggled on a per-tab-group basis.

I'm going to close this now, but feel free to reply with further questions if you have any.
