### ISSUE TITLE
No back/forth arrows with 0.16

### ISSUE THREAD

**Issue by sirlaughalot90** [pjeby/pane-relief#30]
Hi,

I just updated to Obsidian 0.16 (macOS, default theme) and the navigation arrows are gone. Any idea why this has happend and what can be done about it? Thank you!

<img width="661" alt="CleanShot 2022-08-31 at 21 41 23@2x" src="https://user-images.githubusercontent.com/20352339/187767951-e59da3fd-a467-4be2-a6f6-552f2ce6b4c1.png">

**Comment by pjeby** [comment]
Obsidian 0.16 removes the old titlebar by default and replaces it with a native one.  You need to change the "Window frame style" setting (under Settings > Appearance > Advanced) to "Obsidian frame".

If you were using Custom Page Header And Titlebar to add buttons on each pane, you can get them back by enabling "Show tab title bar" under Settings > Appearance > Advanced as well.  This will also get you back pane numbering if you had that turned on, but you should also update to Pane Relief 0.3.1 or higher to correct some styling issues with that.

**Comment by sirlaughalot90** [comment]
Thank you! That was easy. 😄
