### ISSUE TITLE
For 0.16.x, a way to switch to another split pane

### ISSUE THREAD

**Issue by huyz** [pjeby/pane-relief#32]
Now that the mappings mostly deal with tabs and windows, there's a gap for functionality dealing with split panes.

Similar FR: https://forum.obsidian.md/t/keyboard-shortcut-switch-between-split-panels/43284

**Comment by trainbuffer** [comment]
I haven’t gotten myself into anything yet with more than 10+ tabs spread across three or four sliding panes but could see it happening one day. So far I’ve been getting by using optn+1,2,etc or cmd+page up/down to get around and it’s been fine. That said, if we have any modifer keys or fingers left, it would be nice to be able to jump to a particular pane.

**Comment by pjeby** [comment]
Just so you know, there are already existing "focus on tab group to the (left/right/above/below)" commands built into Obsidian that you can assign hotkeys to.  They don't wrap, but you can use PR's first/last commands in combination with them.

**Comment by trainbuffer** [comment]
Ohhh, I did not know about those (or forgot about them). So many settings 😅. Thank you.

**Comment by huyz** [comment]
Oh I forgot about those.  That's good enough. Closing
