### ISSUE TITLE
Pain Relief maximize bug?

### ISSUE THREAD

**Issue by codicem-ex-cinere** [pjeby/pane-relief#35]
## Symptoms
Maximized note content and scroll bar is offset to left by varying amounts with blank space on right.

## Reproduce
In Ob 1.0, with multiple stacked tabs maximize using pain relief command (most noticeable using a note from the middle of stack).

## Solution
Appears to be due to element-style under
`<div class="workspace-leaf has-pane-relief-label mod-active" style="... max-width: --px; ...`

The following stopgap seems to have resolved issue for me.
```
/* Pane Relief maximized width fix */
.workspace-leaf.has-pane-relief-label.mod-active.is-maximized {
    max-width: 100% !important;
}
```

**Comment by pjeby** [comment]
Fix added to 0.4.1, thanks for reporting!
