### ISSUE TITLE
Is it possible to add an option switch in the settings to enable/disable sidebar focusing?

### ISSUE THREAD

**Issue by chenxin0397** [pjeby/pane-relief#38]
Recently, I use a plug-in called PluginGroups to start the software in batches. Every time I start Pane Relief, I have to click Enable/disable sidebar focusing. It is a bit troublesome, so can you add a setting?

**Comment by pjeby** [comment]
Such a setting would make it not work per-workspace, and would not fix any of the other issues created by loading Pane Relief after workspace start, as described in my comments on issue #21.
