### ISSUE TITLE
add screenshots or intuitive interpretations to the README

### ISSUE THREAD

**Issue by YQGong** [pjeby/pane-relief#4]
Hi, thank you for your great work.

Because there were too many words in the README but no screenshots, it took me a long time to figure out what the plug-in did. I think the current Readme may be losing many users, and if the plug-in's functionality could be explained more intuitively, the project would be very popular.

**Comment by pjeby** [comment]
What would this screenshot show?  Everything is a keyboard command, and I'm not sure how you'd visualize the history part, either.  If you have screenshots or other things to offer, feel free to share, but the reason I haven't is because I have no idea what to put.

**Comment by YQGong** [comment]
You are right, visualization is not easy and maybe a screenshot is not a good idea. I drew a sketch to explain the function of this plugin. If you think this is helpful, feel free to use and modify it.

![image](https://user-images.githubusercontent.com/32567917/118465268-4c3a3e80-b734-11eb-95c2-51f3fb251572.png)

[figure.pptx](https://github.com/pjeby/pane-relief/files/6492688/figure.pptx)

**Comment by pjeby** [comment]
Hm.  I wrote this plugin and I don't understand that diagram. :wink:  So I'm not sure how much it would help anything.  I suppose a video (with sound) would probably be the only way to really make it work and I honestly don't care that much, it's not like getting more users for this plugin actually does anything for me.  I'm just making it available so other people can use it.

Now, something I do have planned for a future release is to make the history arrows show a number and be able to be right-clicked to show forward and back history.  A screenshot of that would be possible, or even a short animation to show the numbers and lists changing when switching between panes.  That would probably suffice to get the message across, I imagine.
