### ISSUE TITLE
FR: Shortcuts to move tab to adjacent pane directionally

### ISSUE THREAD

**Issue by ristomatti** [pjeby/pane-relief#43]
I tend to rearrange my code editor tabs depending on what I'm focusing on. It would be great if I could do this with Obsidian aswell.

Aside: It's already helpful to now be able to move a tab left and right. The name of these commands seemed a bit unintuitive though as I initially remapped them the other way around. It seems like the the commands are describing what to do to the previous/next tab and not the tab you've got open. I would expect "Swap tab with next in group" to swap the current tab with the next one ("Move tab right"), but it moves the tab left.

Thanks for the great plugins!

**Comment by pjeby** [comment]
What version of Obsidian are you on?  The swap commands work correctly for me in 1.1.10 and earlier.  (That is, swap with next in group moves the tab to the right, not left.)

**Comment by ristomatti** [comment]
Sorry! You are absolutely correct. After checking it again, I see I got the mapped keys mixed up. Obsidian displays the shortcuts with US layout keys while I'm using FI layout.

In my defense, the mappings show up like this:

Swap with next: `Ctrl + '`, shows as `Ctrl + /`
Swap with prev: `Ctrl + ö`, shows as `` Ctrl + ` ``
