### ISSUE TITLE
Simple Sliding Panes does nothing 

### ISSUE THREAD

**Issue by RhvdG** [pjeby/pane-relief#44]
The Simple Sliding Panes feature doesn't work on my setup. Not in my working vault, but not in a virginal sandbox vault, either.

SYSTEM INFO:
	Obsidian version: v1.1.16
	Installer version: v1.1.16
	Operating system: Darwin Kernel Version 22.2.0: Fri Nov 11 02:04:44 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T8103 22.2.0
	Login status: logged in
	Catalyst license: insider
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: light
	Community theme: Minimal v6.3.2
	Snippets enabled: 2
	Restricted mode: off
	Plugins installed: 21
	Plugins enabled: 16
		1: Minimal Theme Settings v6.3.1
		2: Sentence Navigator v1.3.0
		3: Calendar v1.5.10
		4: Style Settings v1.0.3
		5: Tag Wrangler v0.5.6
		6: Omnisearch v1.12.3
		7: Outliner v4.2.1
		8: Close Similar Tabs v1.2.3
		9: Completr v3.1.3
		10: Hider v1.2.4
		11: Jump to link v0.4.4
		12: Linter v1.10.3
		13: Navigate Cursor History v1.1.0
		14: Recent Files v1.3.5
		15: Smarter Markdown Hotkeys v1.16.3
		16: Pane Relief v0.4.1

**Comment by pjeby** [comment]
Looks like something was broken by the new Obsidian; Obsidian version 1.1.9 and under works fine for me.  So I would suggest downgrading Obsidian if you need the functionality, as I do not know when I will be able to get around to investigating this.

(It would also be helpful if you could provide more detail as to what you mean by "doesn't work".)

**Comment by RhvdG** [comment]
> (It would also be helpful if you could provide more detail as to what you mean by "doesn't work".)

The command simply does nothing at all.

**Comment by pjeby** [comment]
The command doesn't do anything visible unless you have enough side-by-side tab groups; I think you need 2 or 3 before there will be any visible effect.

**Comment by RhvdG** [comment]
That explains. Perhaps in the documentation this should be made more clear. Now there is no indication that it only works with tab _groups_. I don't use those (i.e. not more than one).

**Comment by pjeby** [comment]
Well, it slides *panes*, not tabs.  But I will probably rename it anyway once I drop support for Obsidian 0.15.9.
