### ISSUE TITLE
Cannot edit sidebar

### ISSUE THREAD

**Issue by kmaustral** [pjeby/pane-relief#46]
I found that I can't edit the sidebar anymore with the Pane Relief plugin enabled. I'm using the Insider build: 1.2.3

**Comment by pjeby** [comment]
What do you mean by "edit the sidebar"?

If you mean you can't focus notes or other panes in the sidebar, check the status bar and see if the lock symbol is closed: that's Pane Relief's Focus Lock feature which you can toggle on or off.  If it's closed, click it open and try editing again.

**Comment by kmaustral** [comment]
Thanks. I don't know how became locked. But this fixes it.

It's a great feature.

I hope that others who come across this will find this post.

**Comment by pjeby** [comment]
See https://github.com/pjeby/pane-relief#focus-lock for the feature description; it's been there for a while.  It's possible you just clicked it by accident at some point.
