### ISSUE TITLE
[Bug]: Can't grab the title bar above the left sidebar when using Sliding Pane

### ISSUE THREAD

**Issue by nhan000** [pjeby/pane-relief#48]
Using Sliding Pane and open 3 or more panes:

![image](https://user-images.githubusercontent.com/85216095/237045523-88c459ba-3c63-4893-9c07-987eceaea89c.png)

![image](https://user-images.githubusercontent.com/85216095/237045537-9f0d500a-2d4f-4973-acf5-6c559a469820.png)

**Comment by pjeby** [comment]
That's strange.  It's acting as if the panes are being scrolled *under* the sidebar, but *over* the drag area.  It appears to be an issue with the way the rendering engine handles overlap, which means it's going to be very difficult to fix without rearranging how Obsidian renders things or implementing some sort of weird floating element over the empty space to keep it functioning.

**Comment by nhan000** [comment]
thank you for looking into this. I'll learn to live with it then. Your plugins have helped me so much!

**Comment by pjeby** [comment]
Oh, I'm planning to fix it, it's just going to take a little time.  I have an idea of how to do it, but I don't know if it'll work or what further glitches it might cause.  So I can't promise anything on when just yet.

**Comment by pjeby** [comment]
Okay, 0.5.0 is out with a tentative fix for this and other issues - let me know how it works.

**Comment by nhan000** [comment]
It works great! Thank you so much!
