### ISSUE TITLE
panes moving feature question

### ISSUE THREAD

**Issue by DannyDies** [pjeby/pane-relief#5]
Hello! Is it possible to add moving panes not only between parent and child, but more globally? So that you can move the panes conveniently not only in andy mode?
I don't know js, maybe there is a way to hard code some action combinations. Just for now I using python script to sending keystrokes for moving my panes globally and it has some side-effects. And in that plug nice moving between two panes and maybe there is a better way to implement it.

**Comment by pjeby** [comment]
Sorry, I don't understand what you mean?

**Comment by DannyDies** [comment]
@pjeby Oh, sorry, my bad:D I'm not so fluent in English. Let me try with a bad diagram. In this situation place pane 2 under pane 1, or pane 3 under pane 1. 
![2021-06-11-101321_1366x768_scrot](https://user-images.githubusercontent.com/70198933/121646849-68649d80-ca9e-11eb-97e7-36212a1f5515.png)

or, for instance, any behaviour more similar to, for example, tiling window. That is to put any split in any place sequentially just like in a vertical split. like that:
![moving-splits](https://user-images.githubusercontent.com/70198933/121648863-a367d080-caa0-11eb-9a46-b8a66d23ba6f.gif)

Just only in your plugin for the first time, I met the panes movement. Maybe something like this is possible? For now they are stuck in the parent layouts. For now, it is possible to focus pane 1 and swap it with pane 2 and 3 both and swap payne 2 and payne 3 endlessly. By the way, a great plugin. 

I apologize for the bad explanation, it doesn't always come out the first time, is it better now?

**Comment by pjeby** [comment]
Yes, I understand.  Unfortunately it is rather more difficult to implement, so you may have to keep using the mouse to move them for the moment.

**Comment by DannyDies** [comment]
@pjeby  yeah, I understand. Just mouse is pain. Thanx for your time
