### ISSUE TITLE
Can't toggle sliding panes

### ISSUE THREAD

**Issue by KennyDenvers** [pjeby/pane-relief#51]
I enjoy Pane Relief a lot! But I don't like sliding panes.
By mistake I activated sliding panes -- and cannot get back to the other mode. The "toggle" does not work for me -- with a hotkey that I assigned, by coming from the Ctrl + P commands, also not after disabling, deinstalling, reinstalling, restarting ...
Any advice for me what else I could try? :-)

**Comment by pjeby** [comment]
Sounds like maybe you're using stacked tabs, not sliding panes? Try
toggling that.

**Comment by KennyDenvers** [comment]
Wow, cool! That was spot on! Thx!

**Comment by pjeby** [comment]
Yeah, sliding panes just makes it so you can have as many horizontal split panes as you want (of a fixed size), but you can scroll sideways to see more panes.  Stacked tabs stack the tabs in a single pane.
