### ISSUE TITLE
Number panes/tab no longer working

### ISSUE THREAD

**Issue by tprotopopescu** [pjeby/pane-relief#58]
Not sure if this is the right place to bring this up, so apologies if it is a style settings plugin issue. 

The pane/tab numbers no longer appear (next to the history count and back/forward arrows where they used to be). Tested in a sandbox vault with just pane relief and style settings enabled. 

Let me know what other debugging would be useful. 

`
SYSTEM INFO:
	Obsidian version: v1.6.7
	Installer version: v1.6.7
	Operating system: #1 SMP PREEMPT_DYNAMIC Tue Jul 30 06:37:32 UTC 2024 (9c450d7) 6.4.0-150600.23.17-default
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Base theme: adapt to system
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 2
	Plugins enabled: 2
		1: Pane Relief v0.5.4
		2: Style Settings v1.0.9

RECOMMENDATIONS:
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.
`

**Comment by pjeby** [comment]
It looks like the view header icon was removed in Obsidian 1.6, so I've changed the CSS to be forward compatible.  (I'm still on 1.5.8 myself.)  Update to Pane Relief 0.5.5 and you should get the numbering back.

**Comment by tprotopopescu** [comment]
Thank you! It is nice to have it back.
