### ISSUE TITLE
Close all panes in 1 go

### ISSUE THREAD

**Issue by DutchPete** [pjeby/pane-relief#6]
If I have say 10 panes open, and want to close them because I have finished with them, I have to do `Cmd/CTRL+W` 10x.
It would be useful if with e.g.`Cmd/CTRL+Y` (just an example) I could close all other panes, and with another shortcut close other panes in split.

**Comment by pjeby** [comment]
Obsidian has a "close all other panes" command already built in, so all you need to do is assign a hotkey to it.  Go to "hotkeys" in the preferences, and then type "close" in the search box, it'll come right up.
