### ISSUE TITLE
Numbering on notes

### ISSUE THREAD

**Issue by bibek-maharjan** [pjeby/pane-relief#7]
Can you add the same tab numbering feature as that of obsidian-tabs in pane-relief itself, so that I can use tab numbering with multipane window :)

**Comment by pjeby** [comment]
You can now do this [via CSS](https://github.com/pjeby/pane-relief#pane-numbering), as of version 0.0.12.

**Comment by pjeby** [comment]
As of version 0.2.2, this is now also available as a setting via the Style Settings plugin; see the [release notes](https://github.com/pjeby/pane-relief/releases/tag/0.2.2) for details.
