### ISSUE TITLE
[Feature Request] Open links in a specific pane by right clicking

### ISSUE THREAD

**Issue by Archie-2021** [pjeby/pane-relief#9]
In right click dropdown menu, below open in a new pan add a option to open links in already opened panes, preferably in a sub list that shows the name for all the open panes to choose from them. also adding a visible index number to each pane would be nice to work with it. another (maybe better option) would be to drag and drop links to panes so that they get opened there.

thanks, this plugin is really helpful

**Comment by pjeby** [comment]
You can drag and drop now: just drag the desired item from the history menu to the title area of the desired pane.

**Comment by Archie-2021** [comment]
wow! it works with links inside notes too, that is awesome!
thanks

**Comment by pjeby** [comment]
You can also drag into the file explorer to move the file somewhere else.  Quick Explorer supports all the same features for dragging files, too.  Anyway, I'm going to close this issue since it sounds like you have what you wanted.
